
server:
  port: 8089

mybatis-plus:
  global-config:
    banner: false



spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://121.41.115.229:3306/yubin?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: yubin
    password: Azyz7236
  main:
    banner-mode: off
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  mvc:
    static-path-pattern: /images/**
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  suffix: .jsp

  mail:
    host: smtp.qq.com #发送邮件服务器
    from: tmk-sliy@qq.com # 发送邮件的地址，和上面username一致
    username: tmk-sliy@qq.com #发送邮件的邮箱地址
    password: msogxtvbyfradgdg #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties:
      mail:
        smtp:
          port: 465 #端口号465或587
          starttls:
            enable: true
            required: true
          ssl.enable: true
    default-encoding: utf-8






